version: '3.5' 

services: 

    db:
      image: postgres
      restart: unless-stopped
      environment:
        - POSTGRES_PASSWORD=example

    backend: 
      build: /home/leo/Desktop/devOpsDocker/1/1.11/teht/
      ports:
        - 8000:8000
      environment:
        - REDIS=redis
        - FRONT_URL=http://localhost:5000
        - DB_USERNAME=postgres
        - DB_PASSWORD=example
        - DB_HOST=db
      container_name: back
      depends_on: 
         - db

    frontend: 
      build: /home/leo/Desktop/devOpsDocker/1/1.10/teht/
      ports:
        - 5000:5000
      environment:
        - API_URL=http://localhost:8000
      container_name: front

    nginx:
      image: nginx
      volumes:
       - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
       - "80:80"
      depends_on:
        - backend
        - frontend

    redis: 
      image: redis


