version: '3.5' 

volumes:
  model:
  images:

services: 

    training:
      build: /home/leo/Desktop/devOpsDocker/2/2.7/ml-kurkkumopo-training/
      volumes:
        - model:/src/model
        - images:/src/imgs

    backy: 
      build: /home/leo/Desktop/devOpsDocker/2/2.7/ml-kurkkumopo-backend/
      ports:
        - 5000:5000
      volumes:
        - model:/src/model
      container_name: bac
      depends_on: 
         - training

    fronty: 
      build: /home/leo/Desktop/devOpsDocker/2/2.7/ml-kurkkumopo-frontend/
      ports:
        - 3000:3000
      container_name: fron

