version: '3.5' 

services: 

    backend: 
      build: /home/leo/Desktop/devOpsDocker/1/1.11/teht/
      ports:
        - 8000:8000
      environment:
        - REDIS=redis
        - FRONT_URL=http://localhost:5000
      container_name: back

    frontend: 
      build: /home/leo/Desktop/devOpsDocker/1/1.10/teht/
      ports:
        - 5000:5000
      environment:
        - API_URL=http://localhost:8000
      container_name: front

    redis: 
      image: redis

